id: ACCB5D929
title: .txt
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:21:34.977443
  last_modified_at: 2022-03-01 21:21:34.977449
